// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjnsh2hMYIKrIai-XTQtkIgtR3OmH3ypA',
    appId: '1:522591347273:web:8905d1660dd626e8459598',
    messagingSenderId: '522591347273',
    projectId: 'quickpay-cdc0e',
    authDomain: 'quickpay-cdc0e.firebaseapp.com',
    storageBucket: 'quickpay-cdc0e.firebasestorage.app',
    measurementId: 'G-7HZQDBSXFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb_bew_oJ-CruufvQ6b07SYu3smznLORQ',
    appId: '1:522591347273:android:4ee785cf39436cf4459598',
    messagingSenderId: '522591347273',
    projectId: 'quickpay-cdc0e',
    storageBucket: 'quickpay-cdc0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsTkTVxK3CyPMYKLtrKkla1VH9tDOPD7U',
    appId: '1:522591347273:ios:48df0f68c0f7e1c4459598',
    messagingSenderId: '522591347273',
    projectId: 'quickpay-cdc0e',
    storageBucket: 'quickpay-cdc0e.firebasestorage.app',
    iosBundleId: 'com.example.quickpay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsTkTVxK3CyPMYKLtrKkla1VH9tDOPD7U',
    appId: '1:522591347273:ios:48df0f68c0f7e1c4459598',
    messagingSenderId: '522591347273',
    projectId: 'quickpay-cdc0e',
    storageBucket: 'quickpay-cdc0e.firebasestorage.app',
    iosBundleId: 'com.example.quickpay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjnsh2hMYIKrIai-XTQtkIgtR3OmH3ypA',
    appId: '1:522591347273:web:35049c91ad6955ca459598',
    messagingSenderId: '522591347273',
    projectId: 'quickpay-cdc0e',
    authDomain: 'quickpay-cdc0e.firebaseapp.com',
    storageBucket: 'quickpay-cdc0e.firebasestorage.app',
    measurementId: 'G-2F1NCTW977',
  );
}
